### PR TITLE
Add wild card at the end of the string

### PR DESCRIPTION
**Pull request by brunocasanova**
Add wild card at the end of the string and change readme.

### CODE REVIEW

**Comment by cusspvz** [comment]
For future reference, we don't need length tests since the output entire check are doing the job.

**Comment by cusspvz** [comment]
Thanks mate! :)

**Comment by brunocasanova** [comment]
O'raity maity! arghh!

**Comment by cusspvz** [comment]
@brunocasanova published!

``` bash
MacBook-Pro-de-JM:auto-advanced-search josemoreira$ npm publish
+ auto-advanced-search@0.0.3
```

**Comment by cusspvz** [comment]
Next time don't forget to describe changes on `CHANGELOG.md` so we can track them easily. :p

**Pull request merged**
